name: Build & Publish Release APK

on:
  push:
    branches:
        - master

jobs:
  Gradle:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: setup jdk
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Make Gradle executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      run: ./gradlew 
      
    - name: Publish Release APK
      uses: marp-team/setup-android@v2
      with:
        project-path: app
        build-script: assembleRelease
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    