name: Android Sandbox

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  test:
    name: Start the Virtual Machine
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Read a File from repo
        run: echo "$(cat CHLOG.md)"