name: Android Sandbox

permissions:
  contents: write

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    name: Start the Virtual Machine
    runs-on: ubuntu-latest
    steps:
      - name: Check Commit Message
        id: commit_check
        run: |
          commit_message="${{ github.event.head_commit.message }}"
          regex="^Release v([0-9]+\.[0-9]+\.[0-9]+)"
          if [[ $commit_message =~ $regex ]]; then
              version="${BASH_REMATCH[1]}"
              echo "::set-output name=release_commit::true"
              echo "::set-output name=version::$version"
          else 
              echo "::set-output name=release_commit::false"
          fi;

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run Workflow
        if: steps.commit_check.outputs.release_commit == 'true'
        run: echo SuccessFully Done
